### ISSUE TITLE
How to Use?

### ISSUE THREAD

**Issue by rizkysyazuli** [RamadhanAmizudin/Wordpress-scanner#40]
I've downloaded the latest release and when i run the script, it showing me this:

```
[+] Target: http://1
[+] Start Time: 30-05-2016 10:59AM
[-] This site does not seem to be running WordPress!
[-] No theme was found

[+] Looking for visible plugins on homepage
[-] No plugin was found

[+] Finish Scan at 30-05-2016 10:59AM
[+] Total time taken is: 0 seconds
```

seems it doesn't detect my WP. any idea what i'm doing wrong? right now the scanner script sits inside a folder under my WP installation. like this:

```
- public_html
  - Wordpress-scanner-3.1.0
    - app.php
    - ...
  - ... (wp-config.php, wp-content, etc)
```

**Comment by RamadhanAmizudin** [comment]
normally you would just run by using following command
`php app.php -d -u <url>`

**Comment by d0n601** [comment]
I wrote this a white ago, expands slightly on what @RamadhanAmizudin said above,
[owasp-wordpress-vulnerability-scanner/](https://ryankozak.com/owasp-wordpress-vulnerability-scanner/)
