### ISSUE TITLE
Updating the database.

### ISSUE THREAD

**Issue by IvRRimum** [RamadhanAmizudin/Wordpress-scanner#42]
Hey, I see the current database is outdated.

Is there some kind of script or utility that pulls all the newest version vulnerabilities, plugins, etc?

**Comment by RamadhanAmizudin** [comment]
Hey, unfortunately there's no script/utility for updating those information. 
You can always use '--wpvulndb' option in order to use data from https://wpvulndb.com/.

Thanks.
